// Autogenerated from Pigeon (v3.2.6), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import
import 'dart:async';
import 'dart:typed_data' show Uint8List, Int32List, Int64List, Float64List;

import 'package:flutter/foundation.dart' show WriteBuffer, ReadBuffer;
import 'package:flutter/services.dart';

class _Native2FlutterCodec extends StandardMessageCodec {
  const _Native2FlutterCodec();
}

abstract class Native2Flutter {
  static const MessageCodec<Object?> codec = _Native2FlutterCodec();

  void onClick(bool forward);
  static void setup(Native2Flutter? api, {BinaryMessenger? binaryMessenger}) {
    {
      final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.Native2Flutter.onClick', codec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        channel.setMessageHandler(null);
      } else {
        channel.setMessageHandler((Object? message) async {
          assert(message != null,
              'Argument for dev.flutter.pigeon.Native2Flutter.onClick was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final bool? arg_forward = (args[0] as bool?);
          assert(arg_forward != null,
              'Argument for dev.flutter.pigeon.Native2Flutter.onClick was null, expected non-null bool.');
          api.onClick(arg_forward!);
          return;
        });
      }
    }
  }
}
